### ISSUE TITLE
Deploy L2 Contracts on OP Chain

### ISSUE THREAD

**Issue by ABMNBLSNWMN** [thenamespace/namespace-contracts-v2#27]
Deploy the existing contracts to the OP chain.

**Comment by nenadmitt** [comment]
Contracts deployed and verified
controller: https://optimistic.etherscan.io/address/0x5C1220C4C5D75aC2d0A2f893995b5eCec98F3Aa6
emitter: https://optimistic.etherscan.io/address/0x87516B5518a6548433AB97aE59b15B1A31472F11
resolver: https://optimistic.etherscan.io/address/0xD8de4F5D7117BA37bA171ec9180Da798056f2CEd
registryProxy: https://optimistic.etherscan.io/address/0x3D13a8d0A2aF4Ec81b52d61F519976fC64596900
registryResolver: https://optimistic.etherscan.io/address/0x0798278Ff2c8aD096447B5C368Ce682118D87f63
tokenMetadata: https://optimistic.etherscan.io/address/0xe4338F5e7C46F7CfdD69c3bAc3273584A1953126
